# $FreeBSD$

SRCS+= syscalls-fake.c
CLEANFILES+= syscalls-fake.c

syscalls-fake.c: ${.CURDIR}/../../sys/kern/syscalls.master
	sh ${.CURDIR}/../../tools/tools/shlib-compat/makesyscalls-fake.sh \
		${.CURDIR}/../../sys/kern/syscalls.master > ${.TARGET}

